# Generated by Django 5.2.5 on 2025-11-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0003_remove_product_category_id_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
