# Generated by Django 5.2.5 on 2025-11-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0005_alter_product_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
