# Generated by Django 5.2.5 on 2025-11-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
